%% Use Case: Select Slot
sequenceDiagram
    actor ClientUser
    participant SlotReservation

    ClientUser->>SlotReservation: reserve(calcomReservationId: String)
    alt Slot no longer available
        ClientUser->>SlotReservation: release()
        ClientUser->>SlotReservation: reserve(calcomReservationId: String)
    end
    SlotReservation-->>ClientUser: slot reservation state