import type { DetectorConfig } from "./anomaly.types.js";

export const ANOMALY_DETECTOR_CONFIGS: DetectorConfig[] = [
  {
    key: "cost_spike_global_daily",
    anomalyType: "cost_spike",
    dimensionType: "global",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "spike",
    thresholdMultiplier: 1.8,
    minAbsoluteDelta: 100,
    minExpectedValue: 50,
    enabled: true,
    implemented: true,
  },
  {
    key: "cost_drop_global_daily",
    anomalyType: "cost_drop",
    dimensionType: "global",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "drop",
    thresholdMultiplier: 0.45,
    minAbsoluteDelta: 100,
    minExpectedValue: 50,
    enabled: true,
    implemented: true,
  },
  {
    key: "service_cost_anomaly_daily",
    anomalyType: "service_cost_anomaly",
    dimensionType: "service",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "same_weekday_4w",
    ruleType: "spike",
    thresholdMultiplier: 1.75,
    minAbsoluteDelta: 50,
    minExpectedValue: 20,
    enabled: true,
    implemented: true,
  },
  {
    key: "region_cost_anomaly_daily",
    anomalyType: "region_cost_anomaly",
    dimensionType: "region",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "same_weekday_4w",
    ruleType: "spike",
    thresholdMultiplier: 1.75,
    minAbsoluteDelta: 50,
    minExpectedValue: 20,
    enabled: true,
    implemented: true,
  },
  {
    key: "sub_account_cost_anomaly_daily",
    anomalyType: "sub_account_cost_anomaly",
    dimensionType: "sub_account",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "same_weekday_4w",
    ruleType: "spike",
    thresholdMultiplier: 1.75,
    minAbsoluteDelta: 50,
    minExpectedValue: 20,
    enabled: true,
    implemented: true,
  },
  {
    key: "tag_cost_anomaly_daily",
    anomalyType: "tag_cost_anomaly",
    dimensionType: "tag",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "spike",
    thresholdMultiplier: 1.8,
    minAbsoluteDelta: 30,
    minExpectedValue: 10,
    enabled: true,
    implemented: true,
    tagKey: "environment",
  },
  {
    key: "usage_spike_global_daily",
    anomalyType: "usage_spike",
    dimensionType: "global",
    measureType: "usage_quantity",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "spike",
    thresholdMultiplier: 1.8,
    minAbsoluteDelta: 100,
    minExpectedValue: 50,
    enabled: true,
    implemented: true,
  },
  {
    key: "usage_drop_global_daily",
    anomalyType: "usage_drop",
    dimensionType: "global",
    measureType: "usage_quantity",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "drop",
    thresholdMultiplier: 0.45,
    minAbsoluteDelta: 100,
    minExpectedValue: 50,
    enabled: true,
    implemented: true,
  },
  {
    key: "usage_mismatch_global_daily",
    anomalyType: "usage_mismatch",
    dimensionType: "global",
    measureType: "cost_per_unit",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "mismatch",
    thresholdMultiplier: 1.6,
    minAbsoluteDelta: 0.05,
    minExpectedValue: 0.01,
    enabled: true,
    implemented: true,
  },
  {
    key: "idle_cost_resource_daily",
    anomalyType: "idle_cost",
    dimensionType: "resource",
    measureType: "cpu_avg",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "idle",
    thresholdMultiplier: 1,
    minAbsoluteDelta: 10,
    minExpectedValue: 10,
    enabled: true,
    implemented: true,
    metadata: {
      maxCpuThreshold: 10,
      maxMemoryThreshold: 20,
      minCostThreshold: 10,
    },
  },
  {
    key: "data_transfer_spike_daily",
    anomalyType: "data_transfer_spike",
    dimensionType: "service",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "spike",
    thresholdMultiplier: 2,
    minAbsoluteDelta: 20,
    minExpectedValue: 10,
    enabled: false,
    implemented: false,
  },
  {
    key: "storage_growth_daily",
    anomalyType: "storage_growth",
    dimensionType: "service",
    measureType: "usage_quantity",
    granularity: "daily",
    baselineType: "rolling_median",
    ruleType: "trend_break",
    thresholdMultiplier: 1.5,
    minAbsoluteDelta: 10,
    minExpectedValue: 10,
    enabled: false,
    implemented: false,
  },
  {
    key: "pricing_rate_change_daily",
    anomalyType: "pricing_rate_change",
    dimensionType: "service",
    measureType: "cost_per_unit",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "mismatch",
    thresholdMultiplier: 1.4,
    minAbsoluteDelta: 0.02,
    minExpectedValue: 0.01,
    enabled: false,
    implemented: false,
  },
  {
    key: "commitment_coverage_drop_daily",
    anomalyType: "commitment_coverage_drop",
    dimensionType: "global",
    measureType: "coverage_percent",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "drop",
    thresholdMultiplier: 0.75,
    minAbsoluteDelta: 5,
    minExpectedValue: 10,
    enabled: false,
    implemented: false,
  },
  {
    key: "recurring_pattern_break_hourly",
    anomalyType: "recurring_pattern_break",
    dimensionType: "service",
    measureType: "effective_cost",
    granularity: "hourly",
    baselineType: "same_hour_7d",
    ruleType: "trend_break",
    thresholdMultiplier: 1.6,
    minAbsoluteDelta: 10,
    minExpectedValue: 10,
    enabled: false,
    implemented: false,
  },
  {
    key: "change_event_correlated_daily",
    anomalyType: "change_event_correlated",
    dimensionType: "resource",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "spike",
    thresholdMultiplier: 1.5,
    minAbsoluteDelta: 20,
    minExpectedValue: 10,
    enabled: false,
    implemented: false,
  },
  {
    key: "forecast_deviation_daily",
    anomalyType: "forecast_deviation",
    dimensionType: "global",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "forecast",
    thresholdMultiplier: 1.5,
    minAbsoluteDelta: 50,
    minExpectedValue: 50,
    enabled: false,
    implemented: false,
  },
  {
    key: "resource_cost_anomaly_daily",
    anomalyType: "resource_cost_anomaly",
    dimensionType: "resource",
    measureType: "effective_cost",
    granularity: "daily",
    baselineType: "rolling_7d",
    ruleType: "spike",
    thresholdMultiplier: 1.7,
    minAbsoluteDelta: 15,
    minExpectedValue: 10,
    enabled: false,
    implemented: false,
  },
];
