import { Router } from "express";
import adminClientsRoutes from "../admin/admin-clients/admin-clients.routes.js";
import adminDemoRequestsRoutes from "../admin/admin-demo-requests/admin-demo-requests.routes.js";
import adminBillingUploadsRoutes from "../admin/admin-billing-uploads/admin-billing-uploads.routes.js";
import adminCloudConnectionsRoutes from "../admin/admin-cloud-connections/admin-cloud-connections.routes.js";
import adminAnnouncementsRoutes from "../admin/admin-announcements/admin-announcements.routes.js";
import adminAuthRoutes from "../admin/admin-auth/admin-auth.routes.js";
import authRoutes from "../auth/auth.routes.js";
import awsAutoCloudConnectionsRoutes from "../cloud-connections/aws/auto-connection/cloud-connections.routes.js";
import awsManualConnectionRoutes from "../cloud-connections/aws/manual-connection/manual-connection.routes.js";
import scheduleDemoRoutes from "../schedule-demo/schedule-demo.routes.js";
import billingRoutes from "../billing/billing.routes.js";
import dashboardRoutes from "../dashboard/dashboard.routes.js";
import uploadDashboardRoutes from "../upload-dashboard/upload-dashboard.routes.js";
import awsExportFileEventRoutes from "../cloud-connections/aws/exports/aws-export-file-event.routes.js";
import clientAnnouncementsRoutes from "../client-announcements/client-announcements.routes.js";
import supportTicketsRoutes from "../support-tickets/support-tickets.routes.js";
import supportMeetingsRoutes from "../support-meetings/support-meetings.routes.js";
import anomalyRoutes from "../dashboard/anomaly-alerts/anomaly.routes.js";
import organizationUsersRoutes from "../organization-users/organization-users.routes.js";
import reportRoutes from "../dashboard/report/report.routes.js";
import instancesInventoryRoutes from "../inventory/aws/ec2/instances/instances-inventory.routes.js";
import ec2ReportsRoutes from "../ec2/reports/ec2-reports.routes.js";
const router = Router();

router.use(scheduleDemoRoutes);
router.use(authRoutes);
router.use(adminAuthRoutes);
router.use(awsAutoCloudConnectionsRoutes);
router.use(awsManualConnectionRoutes);
router.use(billingRoutes);
router.use(dashboardRoutes);
router.use(uploadDashboardRoutes);
router.use(adminClientsRoutes);
router.use(adminDemoRequestsRoutes);
router.use(adminBillingUploadsRoutes);
router.use(adminCloudConnectionsRoutes);
router.use(adminAnnouncementsRoutes);
router.use(clientAnnouncementsRoutes);
router.use(supportTicketsRoutes);
router.use(supportMeetingsRoutes);
router.use(organizationUsersRoutes);
router.use(awsExportFileEventRoutes);
router.use(anomalyRoutes);
router.use(reportRoutes);
router.use(instancesInventoryRoutes);
router.use(ec2ReportsRoutes);

export default router;

